FROM node:22 AS provider

# RUN apt update

# RUN npm install -g typescript

WORKDIR /app

COPY package*.json /app/

RUN npm install

FROM node:22-slim

ENV TZ=Asia/Kolkata
ENV NODE_ENV=development
ENV NEXT_PUBLIC_HOST='https://ticketing.dev'
ENV NODE_TLS_REJECT_UNAUTHORIZED='0'

WORKDIR /app

COPY --from=provider /app/node_modules /app/node_modules

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]