POST https://ms.mrityunjay.tech/api/users/signup
Content-Type: application/json

{
    "email": "test01@ms.mrityunjay.tech",
    "password": "pass1234"
}

###
GET https://ms.mrityunjay.tech/api/users/currentuser
Cookie: session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkyTTJJelltSTRNak5tWVdFNE9XSmtaREl5TW1ZMFpTSXNJbVZ0WVdsc0lqb2lkR1Z6ZERBeFFHMXpMbTF5YVhSNWRXNXFZWGt1ZEdWamFDSXNJbWxoZENJNk1UY3hOVEUxTnprME5Dd2laWGh3SWpveE56RTFNalEwTXpRMGZRLmRpWkJQd1RuaFhkSDlDMWZ1TWRWSE96a0lGeEV2U2FZT0xiV2JUeEdkR1kifQ==; path=/; secure; httponlyz

### List Tickets
GET https://ms.mrityunjay.tech/api/tickets

### Create Ticket
POST https://ms.mrityunjay.tech/api/tickets
Content-Type: application/json
Cookie: session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkyTTJJelltSTRNak5tWVdFNE9XSmtaREl5TW1ZMFpTSXNJbVZ0WVdsc0lqb2lkR1Z6ZERBeFFHMXpMbTF5YVhSNWRXNXFZWGt1ZEdWamFDSXNJbWxoZENJNk1UY3hOVEUxTnprME5Dd2laWGh3SWpveE56RTFNalEwTXpRMGZRLmRpWkJQd1RuaFhkSDlDMWZ1TWRWSE96a0lGeEV2U2FZT0xiV2JUeEdkR1kifQ==; path=/; secure; httponly

{
    "title": "Ticket - 1",
    "price": 4.99
}

### Get Ticket
GET https://ms.mrityunjay.tech/api/tickets/66379ad6c826a08f81c1c38c

### Update Ticket
PUT https://ms.mrityunjay.tech/api/tickets/66379ad6c826a08f81c1c38c
Content-Type: application/json
Cookie: session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkyTTJJelltSTRNak5tWVdFNE9XSmtaREl5TW1ZMFpTSXNJbVZ0WVdsc0lqb2lkR1Z6ZERBeFFHMXpMbTF5YVhSNWRXNXFZWGt1ZEdWamFDSXNJbWxoZENJNk1UY3hOVEUxTnprME5Dd2laWGh3SWpveE56RTFNalEwTXpRMGZRLmRpWkJQd1RuaFhkSDlDMWZ1TWRWSE96a0lGeEV2U2FZT0xiV2JUeEdkR1kifQ==; path=/; secure; httponly

{
    "title": "Ticket - 1",
    "price": 5.99
}

### List Orders
GET https://ms.mrityunjay.tech/api/orders
Content-Type: application/json
Cookie: session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkyTTJJelltSTRNak5tWVdFNE9XSmtaREl5TW1ZMFpTSXNJbVZ0WVdsc0lqb2lkR1Z6ZERBeFFHMXpMbTF5YVhSNWRXNXFZWGt1ZEdWamFDSXNJbWxoZENJNk1UY3hOVEUxTnprME5Dd2laWGh3SWpveE56RTFNalEwTXpRMGZRLmRpWkJQd1RuaFhkSDlDMWZ1TWRWSE96a0lGeEV2U2FZT0xiV2JUeEdkR1kifQ==; path=/; secure; httponly

### Create an Orders
POST https://ms.mrityunjay.tech/api/orders
Content-Type: application/json
Cookie: session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkyTTJJelltSTRNak5tWVdFNE9XSmtaREl5TW1ZMFpTSXNJbVZ0WVdsc0lqb2lkR1Z6ZERBeFFHMXpMbTF5YVhSNWRXNXFZWGt1ZEdWamFDSXNJbWxoZENJNk1UY3hOVEUxTnprME5Dd2laWGh3SWpveE56RTFNalEwTXpRMGZRLmRpWkJQd1RuaFhkSDlDMWZ1TWRWSE96a0lGeEV2U2FZT0xiV2JUeEdkR1kifQ==; path=/; secure; httponly

{
    "ticketId": "663b3167f5fb85bc6ef7d30d"
}

### Get an Order
GET https://ms.mrityunjay.tech/api/orders/663b3cde5f7375c006ff1c19

### Cancel an Order
DELETE https://ms.mrityunjay.tech/api/orders/66379b0aa9eaa4d69dcaa6b2

### Make payment to an invalid order
POST https://ms.mrityunjay.tech/api/payments
Content-Type: application/json

{
    "orderId": "66379ad6c826a08f81c1c38c",
    "token": "bvdjkferfhsjfjkf3432jknxkfvdfsd"
}

### Make payment to a correct order
POST https://ms.mrityunjay.tech/api/payments
Content-Type: application/json

{
    "orderId": "66379b0aa9eaa4d69dcaa6b2",
    "token": "bvdjkferfhsjfjkf3432jknxkfvdfsd"
}