name: deploy-client-service

on:
  push:
    branches:
      - master
    paths:
      - client/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      # Run commands
      - name: Build Image And Push to Container Registry
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} \
            -t ghcr.io/mrityunjaym/ticketing-client:latest client
          docker push ghcr.io/mrityunjaym/ticketing-client:latest
      # - run: kubectl rollout restart deployment client-depl
