name: deploy-auth-service

on:
  push:
    branches:
      - master
    paths:
      -  auth/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: dprosper/ic-setup-cli@v0.1.2
        with:
          API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          REGION: au-sy
          RESOURCE_GROUP: Default
          INSTALL_PLUGINS: container-registry, container-service
      - run: ibmcloud cr login
      - run: docker build -t au.icr.io/microservices-tut/ticketing-auth:latest auth && docker push au.icr.io/microservices-tut/ticketing-auth:latest
      - run: kubectl rollout restart deployment auth-depl
