name: deploy-tickets-service

on:
  push:
    branches:
      - master
    paths:
      -  tickets/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      # Run commands
      - run: |
          docker build -t ghcr.io/mrityunjaym/ticketing-tickets:latest tickets
          docker push ghcr.io/mrityunjaym/ticketing-tickets:latest
      # - run: kubectl rollout restart deployment tickets-depl
