name: tests-auth

on:
  pull_request:
    paths: 
      - auth/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd auth && npm ci --include=dev && npm run test:ci
